/* Atomic local practice commit coordinator.
   The injected port owns the actual IndexedDB transaction. UI may advance only
   after this function resolves. */

import { nextReview } from './srs.js';
import { buildPracticeAttemptEvent, samePracticeEvent } from './practice-events.js';

const PRACTICE_STORES = Object.freeze([
  'practiceEvents', 'srsV2', 'formalDueClaims', 'dailyLaneClaims',
  'dailyCardClaims', 'attemptPhaseClaims', 'outbox',
]);

const DAY_CONTEXT_STORES = Object.freeze(['dailyCardClaims', 'attemptPhaseClaims']);

/* 同日同卡的第一筆才建 claim，之後只讀不改。phases 不存在 claim 裡，是從
   attemptPhaseClaims 現查——那些列跟 event 同一個 transaction 寫進去，本來就是
   權威紀錄。存進 claim 再更新的話，Today 跟 All 兩個 tab 會變成 read-modify-write
   互相蓋。 */
const ATTEMPT_PHASES = Object.freeze(['first', 'retry-1', 'retry-2']);

function codedError(code, message) {
  const error = new Error(message);
  error.code = code;
  return error;
}

function requiredFunction(value, label) {
  if (typeof value !== 'function') throw codedError('PRACTICE_ADAPTER_INCOMPLETE', `${label} is required`);
  return value;
}

function requiredWorkspace(value) {
  const workspaceId = typeof value === 'string' ? value.trim() : '';
  if (!workspaceId || (!workspaceId.startsWith('anon:') && !workspaceId.startsWith('user:'))) {
    throw codedError('WORKSPACE_ID_INVALID', 'practice commit requires a workspace');
  }
  return workspaceId;
}

function canonicalUuid(value) {
  return typeof value === 'string' ? value.trim().toLowerCase() : value;
}

function canonicalAttemptSnapshot(attempt, createId) {
  const snapshot = attempt && typeof attempt === 'object' && !Array.isArray(attempt)
    ? structuredClone(attempt)
    : {};
  return Object.freeze({
    ...snapshot,
    eventId: canonicalUuid(snapshot.eventId || createId()),
    roundId: canonicalUuid(snapshot.roundId),
    cycleId: canonicalUuid(snapshot.cycleId),
    cardId: canonicalUuid(snapshot.cardId),
    attemptId: canonicalUuid(snapshot.attemptId),
    dayKey: typeof snapshot.dayKey === 'string' ? snapshot.dayKey.trim() : snapshot.dayKey,
  });
}

function rejectCallerDerivedSrs(attempt) {
  for (const field of ['srsBeforeVersion', 'srsAfterVersion', 'srsAfter']) {
    if (Object.hasOwn(attempt, field)) {
      throw codedError(
        'PRACTICE_INPUT_INVALID',
        `${field} is generated by the practice commit coordinator`,
      );
    }
  }
}

function replayCandidate(attempt, existing) {
  const isFormalDue = existing.lane === 'due' && existing.phase === 'first';
  return buildPracticeAttemptEvent({
    ...attempt,
    eventId: existing.eventId,
    occurredAt: attempt.occurredAt || existing.occurredAt,
    ...(isFormalDue ? {
      srsBeforeVersion: existing.srsBeforeVersion,
      srsAfterVersion: existing.srsAfterVersion,
      srsAfter: existing.srsAfter,
    } : {
      srsBeforeVersion: null,
      srsAfterVersion: null,
      srsAfter: null,
    }),
  });
}

function attemptPhaseClaim(workspaceId, attempt, eventId) {
  return {
    workspaceId,
    attemptId: attempt.attemptId,
    phase: attempt.phase,
    eventId,
    cardId: attempt.cardId,
    dayKey: attempt.dayKey,
    lane: attempt.lane,
  };
}

async function readAttemptPhases(tx, workspace, attemptId) {
  const phases = [];
  for (const phase of ATTEMPT_PHASES) {
    // eslint-disable-next-line no-await-in-loop
    if (!await tx.getAttemptPhaseClaim(workspace, attemptId, phase)) break;
    phases.push(phase);
  }
  return phases;
}

function dayContextFromClaim(claim, phases) {
  return {
    phases,
    lane: claim.lane,
    roundId: claim.roundId,
    cycleId: claim.cycleId,
    cycleOrdinal: claim.cycleOrdinal,
    attemptId: claim.attemptId,
  };
}

/* U6 的評分 controller 在送出前得先知道「今天這張卡是不是已經有人評過」，才決定
   這次是 first 還是 retry-N。回傳的形狀就是 resolvePracticePhase 的 existingContext。 */
export async function readPracticeDayContext({
  port,
  workspaceId,
  dayKey,
  cardId,
} = {}) {
  if (!port || typeof port.transaction !== 'function') {
    throw codedError('STORAGE_UNAVAILABLE', 'practice transaction port is unavailable');
  }
  const workspace = requiredWorkspace(workspaceId);
  return port.transaction(DAY_CONTEXT_STORES, 'readonly', async tx => {
    for (const method of ['getDailyCardClaim', 'getAttemptPhaseClaim']) {
      requiredFunction(tx?.[method], `transaction.${method}`);
    }
    const claim = await tx.getDailyCardClaim(workspace, dayKey, canonicalUuid(cardId));
    if (!claim) return null;
    const phases = await readAttemptPhases(tx, workspace, claim.attemptId);
    if (!phases.length) {
      throw codedError(
        'DAILY_CARD_CLAIM_DANGLING',
        'daily-card claim has no committed attempt phase',
      );
    }
    return dayContextFromClaim(claim, phases);
  });
}

async function resolveAttemptPhaseReplay(tx, workspace, attempt, claim) {
  const existing = await tx.getEvent(workspace, claim.eventId);
  if (!existing) {
    throw codedError(
      'ATTEMPT_PHASE_CLAIM_DANGLING',
      'attempt phase claim points to a missing event',
    );
  }
  const candidate = replayCandidate(attempt, existing);
  if (!samePracticeEvent(existing, candidate)) {
    throw codedError(
      'ATTEMPT_PHASE_COLLISION',
      'attempt phase already exists with another payload',
    );
  }
  return {
    status: 'already-committed',
    event: structuredClone(existing),
    srs: existing.srsAfter || null,
  };
}

export async function commitPracticeAttempt({
  port,
  workspaceId,
  attempt,
  now = Date.now(),
  createId,
  deviceId,
} = {}) {
  if (!port || typeof port.transaction !== 'function') {
    throw codedError('STORAGE_UNAVAILABLE', 'practice transaction port is unavailable');
  }
  const workspace = requiredWorkspace(workspaceId);
  const makeId = requiredFunction(createId, 'createId');
  if (!Number.isFinite(now)) throw codedError('PRACTICE_INPUT_INVALID', 'now must be finite');
  const occurredAt = new Date(now).toISOString();
  const attemptSnapshot = canonicalAttemptSnapshot(attempt, makeId);
  rejectCallerDerivedSrs(attemptSnapshot);
  const isFormalDueInput = attemptSnapshot.lane === 'due' && attemptSnapshot.phase === 'first';
  if (!isFormalDueInput && attemptSnapshot.formalGrade != null) {
    throw codedError('PRACTICE_INPUT_INVALID', 'only formal Due first may carry SRS fields');
  }
  const installationId = typeof deviceId === 'string' ? deviceId.trim() : '';
  if (isFormalDueInput && !installationId) {
    throw codedError(
      'PRACTICE_INPUT_INVALID',
      'formal Due commit requires a per-workspace installation ID',
    );
  }

  return port.transaction(PRACTICE_STORES, 'readwrite', async tx => {
    for (const method of [
      'getEvent', 'putEvent', 'putOutbox', 'getSrs', 'putSrs',
      'addFormalDueClaim', 'addDailyLaneClaim',
      'getDailyCardClaim', 'addDailyCardClaim',
      'getAttemptPhaseClaim', 'addAttemptPhaseClaim',
    ]) {
      requiredFunction(tx?.[method], `transaction.${method}`);
    }

    const eventId = attemptSnapshot.eventId;
    const existing = await tx.getEvent(workspace, eventId);
    if (existing) {
      const candidate = replayCandidate(attemptSnapshot, existing);
      if (!samePracticeEvent(existing, candidate)) {
        throw codedError('EVENT_ID_COLLISION', 'event ID already exists with another payload');
      }
      const priorClaim = await tx.getAttemptPhaseClaim(
        workspace, attemptSnapshot.attemptId, attemptSnapshot.phase,
      );
      if (priorClaim && priorClaim.eventId !== existing.eventId) {
        throw codedError(
          'ATTEMPT_PHASE_COLLISION',
          'attempt phase already points to another event',
        );
      }
      if (!priorClaim) {
        const claimed = await tx.addAttemptPhaseClaim(
          workspace,
          attemptPhaseClaim(workspace, attemptSnapshot, existing.eventId),
        );
        if (!claimed) {
          const concurrentClaim = await tx.getAttemptPhaseClaim(
            workspace, attemptSnapshot.attemptId, attemptSnapshot.phase,
          );
          if (!concurrentClaim || concurrentClaim.eventId !== existing.eventId) {
            throw codedError(
              'ATTEMPT_PHASE_COLLISION',
              'attempt phase was claimed by another event',
            );
          }
        }
      }
      return { status: 'already-committed', event: structuredClone(existing), srs: existing.srsAfter || null };
    }

    const priorAttemptPhase = await tx.getAttemptPhaseClaim(
      workspace, attemptSnapshot.attemptId, attemptSnapshot.phase,
    );
    if (priorAttemptPhase) {
      return resolveAttemptPhaseReplay(tx, workspace, attemptSnapshot, priorAttemptPhase);
    }

    const isFormalDue = isFormalDueInput;
    let srsAfter = null;
    let srsBeforeVersion = null;
    let srsAfterVersion = null;

    if (attemptSnapshot.phase === 'first') {
      // R3：跨 Today／All、跨 lane 的唯一 first。key 不含 lane，所以 All 的 sweep
      // 擋得住 Today 的 due，反之亦然。
      const dailyCardClaimed = await tx.addDailyCardClaim(workspace, {
        workspaceId: workspace,
        dayKey: attemptSnapshot.dayKey,
        cardId: attemptSnapshot.cardId,
        lane: attemptSnapshot.lane,
        roundId: attemptSnapshot.roundId,
        cycleId: attemptSnapshot.cycleId,
        cycleOrdinal: attemptSnapshot.cycleOrdinal,
        attemptId: attemptSnapshot.attemptId,
        eventId,
      });
      if (dailyCardClaimed !== true) {
        const winner = await tx.getDailyCardClaim(
          workspace, attemptSnapshot.dayKey, attemptSnapshot.cardId,
        );
        if (!winner) {
          throw codedError(
            'DAILY_CARD_CLAIM_DANGLING',
            'daily-card claim collided but could not be read back',
          );
        }
        const phases = await readAttemptPhases(tx, workspace, winner.attemptId);
        return {
          status: 'daily-card-already-claimed',
          context: dayContextFromClaim(winner, phases.length ? phases : ['first']),
          event: null,
          srs: null,
        };
      }
      const claimRow = {
        workspaceId: workspace,
        cardId: attemptSnapshot.cardId,
        dayKey: attemptSnapshot.dayKey,
        lane: attemptSnapshot.lane,
        eventId,
      };
      const claimed = isFormalDue
        ? await tx.addFormalDueClaim(workspace, {
          ...claimRow, claimKind: 'formal-due',
        })
        : await tx.addDailyLaneClaim(workspace, claimRow);
      if (claimed !== true) {
        return {
          status: isFormalDue ? 'formal-due-already-claimed' : 'daily-lane-already-claimed',
          event: null,
          srs: null,
        };
      }
    }

    const attemptClaimed = await tx.addAttemptPhaseClaim(
      workspace,
      attemptPhaseClaim(workspace, attemptSnapshot, eventId),
    );
    if (!attemptClaimed) {
      const concurrentClaim = await tx.getAttemptPhaseClaim(
        workspace, attemptSnapshot.attemptId, attemptSnapshot.phase,
      );
      if (!concurrentClaim) {
        throw codedError(
          'ATTEMPT_PHASE_CLAIM_DANGLING',
          'attempt phase claim could not be read after collision',
        );
      }
      return resolveAttemptPhaseReplay(tx, workspace, attemptSnapshot, concurrentClaim);
    }

    if (isFormalDue) {
      const current = await tx.getSrs(workspace, attemptSnapshot.cardId);
      srsBeforeVersion = current?.version || 0;
      srsAfterVersion = srsBeforeVersion + 1;
      srsAfter = nextReview(attemptSnapshot.formalGrade, current?.state || {}, now, {
        deviceId: installationId,
      });
    }

    const event = buildPracticeAttemptEvent({
      ...attemptSnapshot,
      eventId,
      occurredAt: attemptSnapshot.occurredAt || occurredAt,
      formalGrade: isFormalDue ? attemptSnapshot.formalGrade : null,
      srsBeforeVersion,
      srsAfterVersion,
      srsAfter,
    });

    const writes = [
      tx.putEvent(workspace, event),
      tx.putOutbox(workspace, event.eventId, {
        workspaceId: workspace,
        eventId: event.eventId,
        status: 'pending',
        event: structuredClone(event),
      }),
    ];
    if (isFormalDue) {
      writes.push(tx.putSrs(workspace, event.cardId, {
        workspaceId: workspace,
        cardId: event.cardId,
        version: srsAfterVersion,
        state: structuredClone(srsAfter),
        sourceEventId: event.eventId,
      }));
    }
    await Promise.all(writes);
    return { status: 'committed', event: structuredClone(event), srs: structuredClone(srsAfter) };
  });
}
